
FAIL Rejecting the fetch event or using preventDefault() causes a network error assert_equals: expected "PASS" but got "FAIL: no controller"

